def openHelp(role="nouser"): #memberikan default value "nouser" ketika tidak diberikan argumen (digunakn sebelum login)
    print("============ HELP ============")
    print("login - untuk melakukan login ke dalam sistem")
    if role == "user" or role == "admin":
        print("carirarity - untuk mencari gadget berdasarkan rarity")
        print("caritahun - untuk mencari gadget berdaasrkan tahun ditemukan")
        if role == 'admin':
            print("tambahitem - untuk menambahkan gadget atau consumable ke dalam inventory")
            print("hapusitem - untuk menghapus gadget atau consumable dari inventory")
            print("ubahjumlah - untuk mengubah jumlah gadget atau consumable pada inventory")
            print("riwayatpinjam - untuk melihat riwayat peminjaman gadget")
            print("riwayatkembali - untuk melihat riwayat gadget yang sudah dikembalikan")
            print("riwayatambil - untuk melihat riwayat pengambilan consumable")
        print("pinjam - untuk meminjam gadget")
        print("kembalikan - untuk mengembalikan gadget yang dipinjam")
        print("minta - untuk meminta consumable")
        print("save - untuk menyimpan perubahan yang telah dilakukan")
    print("help - untuk melihat panduan command")
    print("exit - untuk keluar dari program")